# Branch configuration for alice4_develop_ws
workspace: /home/aeirobot/ROS2/alice4_develop_ws
git_base_url: https://github.com/HERoEHS

branches:
  aeirobot_framework: develop
  aeirobot_state_estimator: develop
  aeirobot_toolbox: develop
  alice_common: develop
  alice_main: develop
  alice_parameters: develop
  alice_simulation: develop
  alice_action_manager: develop
