# Repo branch configuration for alice_mobile_develop
git_base_url: https://github.com/HERoEHS

branches:
  aeirobot_framework: v1.0.2
  aeirobot_toolbox: feature/m1_poc_pc
  alice_mobile_common: develop
  alice_mobile_main: develop
  alice_mobile_parameters: v0.1.0-hotfix
  alice_mobile_jetson: feature/nextrise_2026
  aeirobot_teleoperation: develop
  ROS-TCP-Endpoint: feature/m1_poc
